@startuml

title Download Song

left to right direction
skinparam shadowing false
skinparam roundcorner 10

actor Premium_Χρήστης

boundary Μενού_Επιλογών_Τραγουδιού
boundary Download_Button
boundary Όχι_Αρκετός_Χώρος_Popup

control Έλεγχος_Χώρου
control Κατέβασμα_Τραγουδιού

entity Βάση_Δεδομένων
entity Τοπικό_Σύστημα_Αρχείων

Premium_Χρήστης --> Μενού_Επιλογών_Τραγουδιού : επιλέγει τραγούδι

Μενού_Επιλογών_Τραγουδιού --> Download_Button : click download

Download_Button --> Έλεγχος_Χώρου : request download

Έλεγχος_Χώρου --> Τοπικό_Σύστημα_Αρχείων : check free space
Τοπικό_Σύστημα_Αρχείων --> Έλεγχος_Χώρου : return free space

Έλεγχος_Χώρου --> Κατέβασμα_Τραγουδιού : space OK

Κατέβασμα_Τραγουδιού --> Βάση_Δεδομένων : request song metadata
Βάση_Δεδομένων --> Κατέβασμα_Τραγουδιού : return file URL / path

Κατέβασμα_Τραγουδιού --> Τοπικό_Σύστημα_Αρχείων : save song

Έλεγχος_Χώρου --> Όχι_Αρκετός_Χώρος_Popup : space NOT OK
Όχι_Αρκετός_Χώρος_Popup --> Premium_Χρήστης : show error
Όχι_Αρκετός_Χώρος_Popup --> Μενού_Επιλογών_Τραγουδιού : close popup

@enduml