@startuml name

title Add Song To Playlist

actor User
participant SongView
participant SongController
participant PlaylistService
participant PlaylistAPI
participant PlaylistBackendController
participant PlaylistBackendService
participant PlaylistRepository
database Database

activate SongView
User -> SongView : Right click on song
SongView -> SongView : onSongRightClick()
SongView -> SongView : showContextMenu()
User -> SongView : Click "Add to Playlist"
SongView -> SongView : showPlaylistSelectionDialog()
User -> SongView : Select playlist and confirm
alt "User selected a playlist"
    SongView -> SongController : addSongToPlaylist(songId, playlistId)
    activate SongController
    SongController -> PlaylistService : addSongToPlaylist(songId, playlistId)
    activate PlaylistService
    PlaylistService -> PlaylistService : checkForDuplicate(songId, playlistId)
    PlaylistService --> SongController : Duplicate check result
    alt "No duplicate found"
        PlaylistService -> PlaylistAPI : addSongToPlaylist(songId, playlistId)
        activate PlaylistAPI
        PlaylistAPI -> PlaylistBackendController : addSongToPlaylist(songId, playlistId)
        activate PlaylistBackendController
        PlaylistBackendController -> PlaylistBackendService : addSongToPlaylist(songId, playlistId)
        activate PlaylistBackendService
        PlaylistBackendService -> PlaylistRepository : addSongToPlaylist(songId, playlistId)
        activate PlaylistRepository
        PlaylistRepository -> Database : Execute SQL to add song to playlist
        Database --> PlaylistRepository : Success/Failure
        deactivate PlaylistRepository
        PlaylistBackendService --> PlaylistBackendController : Success/Failure
        deactivate PlaylistBackendService
        PlaylistBackendController --> PlaylistAPI : Success/Failure
        deactivate PlaylistBackendController
        PlaylistAPI --> PlaylistService : Success/Failure
        deactivate PlaylistAPI
        PlaylistService --> SongController : Success/Failure
        deactivate PlaylistService
        SongController --> SongView : Show success/failure message
        deactivate SongController
    else "Duplicate found"
        

        activate PlaylistService
        PlaylistService --> SongController : Duplicate found message
        activate SongController
        deactivate PlaylistService
        SongController --> SongView : Show duplicate message
        deactivate SongController
    end
else "User Selected Favourites"
    SongView -> SongController : addSongToFavourites(songId)
    activate SongController
    SongController -> PlaylistService : addSongToFavourites(songId)
    activate PlaylistService
    PlaylistService -> PlaylistAPI : addSongToFavourites(songId)
    activate PlaylistAPI
    PlaylistAPI -> PlaylistBackendController : addSongToFavourites(songId)
    activate PlaylistBackendController
    PlaylistBackendController -> PlaylistBackendService : addSongToFavourites(songId)
    activate PlaylistBackendService
    PlaylistBackendService -> PlaylistRepository : addSongToFavourites(songId)
    activate PlaylistRepository
    PlaylistRepository -> Database : Execute SQL to add song to favourites
    Database --> PlaylistRepository : Success/Failure
    deactivate PlaylistRepository
    PlaylistBackendService --> PlaylistBackendController : Success/Failure
    deactivate PlaylistBackendService
    PlaylistBackendController --> PlaylistAPI : Success/Failure
    deactivate PlaylistBackendController
    PlaylistAPI --> PlaylistService : Success/Failure
    deactivate PlaylistAPI
    PlaylistService --> SongController : Success/Failure
    deactivate PlaylistService
    SongController --> SongView : Show success/failure message
    deactivate SongController

end

@enduml