@startuml name

title Approve / Reject Artist Request

actor Admin
participant HomeView
participant HomeController
participant ArtistRequestService
participant ArtistRequestAPI
participant ArtistRequestBackendController
participant ArtistRequestBackendService
participant ArtistRequestRepository
database Database

activate HomeView
Admin -> HomeView : Click on "Artist Account Applications"
HomeView -> HomeController : viewArtistRequests()
activate HomeController
HomeController -> ArtistRequestService : getAllArtistRequests()
activate ArtistRequestService
ArtistRequestService -> ArtistRequestAPI : getAllArtistRequests()
activate ArtistRequestAPI
ArtistRequestAPI -> ArtistRequestBackendController : getAllArtistRequests()
activate ArtistRequestBackendController
ArtistRequestBackendController -> ArtistRequestBackendService : getAllArtistRequests()
activate ArtistRequestBackendService
ArtistRequestBackendService -> ArtistRequestRepository : getAllArtistRequests()
activate ArtistRequestRepository
ArtistRequestRepository -> Database : Execute SQL to get all artist requests
Database --> ArtistRequestRepository : Return list of artist requests
ArtistRequestRepository --> ArtistRequestBackendService : Return list of artist requests
deactivate ArtistRequestRepository
ArtistRequestBackendService --> ArtistRequestBackendController : Return list of artist requests
deactivate ArtistRequestBackendService
ArtistRequestBackendController --> ArtistRequestAPI : Return list of artist requests
deactivate ArtistRequestBackendController
ArtistRequestAPI --> ArtistRequestService : Return list of artist requests
deactivate ArtistRequestAPI
ArtistRequestService --> HomeController : Return list of artist requests
deactivate ArtistRequestService
HomeController --> HomeView : Display list of artist requests
deactivate HomeController
Admin -> HomeView : Click on an artist request
HomeView -> HomeView : showArtistRequestDetails()
Admin -> HomeView : Click "Approve" or "Reject"
alt Approve
    HomeView -> HomeController : approveArtistRequest(requestId)
    activate HomeController
    HomeController -> ArtistRequestService : approveArtistRequest(requestId)
    activate ArtistRequestService
    ArtistRequestService -> ArtistRequestAPI : approveArtistRequest(requestId)
    activate ArtistRequestAPI
    ArtistRequestAPI -> ArtistRequestBackendController : approveArtistRequest(requestId)
    activate ArtistRequestBackendController
    ArtistRequestBackendController -> ArtistRequestBackendService : approveArtistRequest(requestId)
    activate ArtistRequestBackendService
    ArtistRequestBackendService -> ArtistRequestRepository : approveArtistRequest(requestId)
    activate ArtistRequestRepository
    ArtistRequestRepository -> Database : Execute SQL to approve artist request
    Database --> ArtistRequestRepository : Success/Failure
    ArtistRequestRepository --> ArtistRequestBackendService : Success/Failure
    deactivate ArtistRequestRepository
    ArtistRequestBackendService --> ArtistRequestBackendController : Success/Failure
    deactivate ArtistRequestBackendService
    ArtistRequestBackendController --> ArtistRequestAPI : Success/Failure
    deactivate ArtistRequestBackendController
    ArtistRequestAPI --> ArtistRequestService : Success/Failure
    deactivate ArtistRequestAPI
    ArtistRequestService --> HomeController : Success/Failure
    deactivate ArtistRequestService
    HomeController --> HomeView : Show success/failure message
    deactivate HomeController
else Reject
    HomeView -> HomeController : rejectArtistRequest(requestId)
    activate HomeController
    HomeController -> ArtistRequestService : rejectArtistRequest(requestId)
    activate ArtistRequestService
    ArtistRequestService -> ArtistRequestAPI : rejectArtistRequest(requestId)
    activate ArtistRequestAPI
    ArtistRequestAPI -> ArtistRequestBackendController : rejectArtistRequest(requestId)
    activate ArtistRequestBackendController
    ArtistRequestBackendController -> ArtistRequestBackendService : rejectArtistRequest(requestId)
    activate ArtistRequestBackendService
    ArtistRequestBackendService -> ArtistRequestRepository : rejectArtistRequest(requestId)
    activate ArtistRequestRepository
    ArtistRequestRepository -> Database : Execute SQL to reject artist request
    Database --> ArtistRequestRepository : Success/Failure
    ArtistRequestRepository --> ArtistRequestBackendService : Success/Failure
    deactivate ArtistRequestRepository
    ArtistRequestBackendService --> ArtistRequestBackendController : Success/Failure
    deactivate ArtistRequestBackendService
    ArtistRequestBackendController --> ArtistRequestAPI : Success/Failure
    deactivate ArtistRequestBackendController
    ArtistRequestAPI --> ArtistRequestService : Success/Failure
    deactivate ArtistRequestAPI
    ArtistRequestService --> HomeController : Success/Failure
    deactivate ArtistRequestService
    HomeController --> HomeView : Show success/failure message
    deactivate HomeController
end

@enduml
