@startuml Register

actor User as Foo
participant RegisterView as Foo1
participant RegisterController as Foo2
participant RegisterService as Foo3
participant RegisterApi as Foo4
participant RegisterBackendController as Foo5
participant RegisterBackendService as Foo6
participant RegisterBackendRepository as Foo7
database Database as Foo8

Foo -> Foo1 : Press Register Button

activate Foo1
Foo1 -> Foo2 : onRegisterButtonClicked(username)

activate Foo2
Foo2 -> Foo3 : onRegisterButtonClicked(username)

activate Foo3
Foo3 -> Foo4 : checkForDuplicateNameOrEmail(username)

activate Foo4
Foo4 -> Foo5 : Get /user/nameOrEmail

activate Foo5
Foo5 -> Foo6 : findUserByNameOrEmail(username)

activate Foo6
Foo6 -> Foo7 : findUserByNameOrEmail(username)

activate Foo7
Foo7 -> Foo8 : Select User By Name or Email Query

Foo8 -> Foo7 : return success / error

alt User found 
    Foo7 -> Foo6 : return success / error
else User not found
    Foo7 -> Foo8 : Insert User Statement
    Foo8 -> Foo7 : return UserInsertSuccess
    return UserInsertSuccess
end

deactivate Foo7

Foo6 -> Foo5 : return success / error
deactivate Foo6

Foo5 -> Foo4 : return success / error
deactivate Foo5

Foo4 -> Foo3 : return success / error
deactivate Foo4

alt User found
    Foo3 -> Foo2 : ShowDuplicateEmailOrUsername()
    deactivate Foo3

    Foo2 -> Foo1 : ShowDuplcateError()
    deactivate Foo2
else User not found
    Foo3 -> Foo2 : RegisterSuccessful()
    Foo2 -> Foo1 : RegisterSuccessful()
    Foo3 -> EventBus : changeToLoginView()
    deactivate Foo2
    deactivate Foo1
end
deactivate Foo2
deactivate Foo1
@enduml