@startuml Register

actor User as Foo
participant RegisterView as Foo1
participant RegisterController as Foo2
participant RegisterService as Foo3
participant RegisterApi as Foo4
participant RegisterBackendController as Foo5
participant RegisterBackendService as Foo6
participant RegisterBackendRepository as Foo7
database Database as Foo8
participant EventBus

Foo -> Foo1 : Press Register Button

activate Foo1
Foo1 -> Foo2 : onRegisterButtonClicked(username)

activate Foo2
Foo2 -> Foo3 : onRegisterButtonClicked(username)

activate Foo3
Foo3 -> Foo4 : checkForDuplicateNameOrEmail(username)

activate Foo4
Foo4 -> Foo5 : GET /user/nameOrEmail

activate Foo5
Foo5 -> Foo6 : findUserByNameOrEmail(username)

activate Foo6
Foo6 -> Foo7 : findUserByNameOrEmail(username)

activate Foo7
Foo7 -> Foo8 : SELECT user

Foo8 --> Foo7 : result

alt User found
    Foo7 --> Foo6 : exists
    Foo6 --> Foo5 : exists
    Foo5 --> Foo4 : exists
    Foo4 --> Foo3 : duplicate found

    Foo3 -> Foo2 : ShowDuplicateEmailOrUsername()
    Foo2 -> Foo1 : ShowDuplicateError()

else User not found
    Foo7 --> Foo6 : not found
    Foo6 -> Foo7 : INSERT user
    Foo7 --> Foo6 : insert success

    Foo6 --> Foo5 : success
    Foo5 --> Foo4 : success
    Foo4 --> Foo3 : success

    Foo3 -> Foo2 : RegisterSuccessful()
    Foo2 -> Foo1 : RegisterSuccessful()

    Foo3 -> EventBus : changeToLoginView()
end

deactivate Foo7
deactivate Foo6
deactivate Foo5
deactivate Foo4
deactivate Foo3
deactivate Foo2
deactivate Foo1

@enduml