/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.example.controller.MainController;

class AppTest {
    @Test void appHasAGreeting() {
        MainController classUnderTest = new MainController();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
