@startuml

title Create Playlist

left to right direction

skinparam shadowing false
skinparam roundcorner 10

' =====================================================
' ACTORS
' =====================================================

actor Γενικός_Χρήστης

' =====================================================
' BOUNDARY OBJECTS
' =====================================================

boundary Μενού_Πλοήγησης
boundary Ίδιο_Όνομα_Popup
boundary Επιτυχής_Δημιουργία_Popup
boundary Playlist_Editor

' =====================================================
' CONTROL OBJECTS
' =====================================================

control Εισαγωγή_Λεπτομερειών 
control Έλεγξε_για_ίδιο_όνομα
control Δημιούργησε_Λίστα_Αναπαραγωγής
control Playlist_Options

' =====================================================
' ENTITY OBJECTS
' =====================================================

entity Βάση_Δεδομένων

' =====================================================
' INTERACTIONS
' =====================================================

Γενικός_Χρήστης --> Μενού_Πλοήγησης
Μενού_Πλοήγησης --> Playlist_Options : Eπιλέγει Δημιουργία νέας λίστας Αναπαραγωγής
Playlist_Options --> Playlist_Editor 
Playlist_Editor --> Εισαγωγή_Λεπτομερειών 
Εισαγωγή_Λεπτομερειών --> Μενού_Πλοήγησης : Ο Χρήστης επιλέγει Ακύρωση
Εισαγωγή_Λεπτομερειών --> Έλεγξε_για_ίδιο_όνομα : Ο Χρήστης εισαγάγει το όνομα, τη περιγραφή της λίστας και επιλέγει αν είναι ιδιωτική ή δημόσια
Έλεγξε_για_ίδιο_όνομα --> Δημιούργησε_Λίστα_Αναπαραγωγής : Δεν υπάρχει
Δημιούργησε_Λίστα_Αναπαραγωγής --> Βάση_Δεδομένων
Δημιούργησε_Λίστα_Αναπαραγωγής --> Επιτυχής_Δημιουργία_Popup
Έλεγξε_για_ίδιο_όνομα --> Ίδιο_Όνομα_Popup : Υπάρχει
Ίδιο_Όνομα_Popup --> Εισαγωγή_Λεπτομερειών : Επιστροφή
Επιτυχής_Δημιουργία_Popup --> Γενικός_Χρήστης
Ίδιο_Όνομα_Popup --> Γενικός_Χρήστης

@enduml
