@startuml

title Create Playlist

left to right direction

skinparam shadowing false
skinparam roundcorner 10

' =====================================================
' ACTORS
' =====================================================

actor Γενικός_Χρήστης

' =====================================================
' BOUNDARY OBJECTS
' =====================================================

boundary Μενού_Πλοήγησης
boundary Οθόνη_Playlists
boundary Ίδιο_Όνομα_Toast
boundary Επιτυχής_Δημιουργία_Toast
boundary Playlist_Editor

' =====================================================
' CONTROL OBJECTS
' =====================================================

control Εισαγωγή_Λεπτομερειών 
control Έλεγξε_για_ίδιο_όνομα
control Δημιούργησε_Λίστα_Αναπαραγωγής



' =====================================================
' ENTITY OBJECTS
' =====================================================

entity Βάση_Δεδομένων

' =====================================================
' INTERACTIONS
' =====================================================

Γενικός_Χρήστης --> Μενού_Πλοήγησης
Μενού_Πλοήγησης -->  Οθόνη_Playlists
Οθόνη_Playlists --> Playlist_Editor : Ο Χρήστης επιλέγει "Δημιουργία νέας λίστας Αναπαραγωγής"
Playlist_Editor --> Εισαγωγή_Λεπτομερειών 
Εισαγωγή_Λεπτομερειών --> Μενού_Πλοήγησης : Ο Χρήστης επιλέγει "Ακύρωση"
Εισαγωγή_Λεπτομερειών --> Έλεγξε_για_ίδιο_όνομα : Ο Χρήστης εισαγάγει το όνομα, τη περιγραφή της λίστας και επιλέγει αν είναι ιδιωτική ή δημόσια
Έλεγξε_για_ίδιο_όνομα --> Δημιούργησε_Λίστα_Αναπαραγωγής : Δεν υπάρχει
Δημιούργησε_Λίστα_Αναπαραγωγής --> Βάση_Δεδομένων
Δημιούργησε_Λίστα_Αναπαραγωγής --> Επιτυχής_Δημιουργία_Toast
Έλεγξε_για_ίδιο_όνομα --> Ίδιο_Όνομα_Toast : Υπάρχει
Ίδιο_Όνομα_Toast --> Εισαγωγή_Λεπτομερειών : Επιστροφή
Επιτυχής_Δημιουργία_Toast --> Γενικός_Χρήστης
Ίδιο_Όνομα_Toast --> Γενικός_Χρήστης

@enduml
