@startuml

title Download Song

left to right direction

skinparam shadowing false
skinparam roundcorner 10

' =====================================================
' ACTORS
' =====================================================

actor Γενικός_Χρήστης

' =====================================================
' BOUNDARY OBJECTS
' =====================================================


boundary Μενού_Επιλογών_Τραγουδιού
boundary Όχι_Αρκετός_Χώρος_Popup

' =====================================================
' CONTROL OBJECTS
' =====================================================

control Έλεγχος_Premium
control Έλεγχος_Χώρου
control Κατέβασμα_Τραγουδιού


' =====================================================
' ENTITY OBJECTS
' =====================================================

entity Βάση_Δεδομένων
entity Τοπικό_Σύστημα_Αρχείων

' =====================================================
' INTERACTIONS
' =====================================================

Γενικός_Χρήστης --> Μενού_Επιλογών_Τραγουδιού: ροή Αναζήτηση Τραγουδιού (Βλ. Search Content), επιλέγει το τραγούδι που θέλει
Μενού_Επιλογών_Τραγουδιού --> Έλεγχος_Premium
Έλεγχος_Premium --> Download_Button : Premium =/= 0 : show
Download_Button --> Βάση_Δεδομένων : ναι-Σύστημα αντλεί αρχείο τραγουδιού
Download_Button --> Έλεγχος_Χώρου : ναι
Έλεγχος_Χώρου --> Τοπικό_Σύστημα_Αρχείων : ελέγχει χώρο, βρίσκει filepath downloads
Έλεγχος_Χώρου --> Κατέβασμα_Τραγουδιού : χώρος Αρκετός
Κατέβασμα_Τραγουδιού --> Τοπικό_Σύστημα_Αρχείων : τραγούδι κατεβαίνει


Έλεγχος_Χώρου --> Όχι_Αρκετός_Χώρος_Popup : όχι αρκετός χώρος
Όχι_Αρκετός_Χώρος_Popup --> Γενικός_Χρήστης
Όχι_Αρκετός_Χώρος_Popup --> Μενού_Επιλογών_Τραγουδιού : Close Popup

@enduml