@startuml

title Follow/Unfollow Artist

left to right direction

skinparam shadowing false
skinparam roundcorner 10

' =====================================================
' ACTORS
' =====================================================

actor Γενικός_Χρήστης

' =====================================================
' BOUNDARY OBJECTS
' =====================================================

boundary Μενού_Πληροφοριών_Καλλιτέχνη
boundary Popup_Error
boundary Popup_Απεγγραφής
boundary Popup_Εγγραφής

' =====================================================
' CONTROL OBJECTS
' =====================================================

control Έλεγξε_Αν_Ήδη_Ακολουθεί
control Απεγγραφή_Από_Καλλιτέχνη
control Εγγραφή_Σε_Καλλιτέχνη

' =====================================================
' ENTITY OBJECTS
' =====================================================

entity Βάση_Δεδομένων

' =====================================================
' USE CASES
' =====================================================

usecase Αναζήτηση_Καλλιτέχνη_Search_Content


' =====================================================
' INTERACTIONS
' =====================================================

Γενικός_Χρήστης --> Αναζήτηση_Καλλιτέχνη_Search_Content
Αναζήτηση_Καλλιτέχνη_Search_Content --> Μενού_Πληροφοριών_Καλλιτέχνη: επιλέγει το καλλιτέχνη που θέλει
Μενού_Πληροφοριών_Καλλιτέχνη --> Έλεγξε_Αν_Ήδη_Ακολουθεί : Επιλέγει Follow 
Έλεγξε_Αν_Ήδη_Ακολουθεί --> Απεγγραφή_Από_Καλλιτέχνη : ναι
Έλεγξε_Αν_Ήδη_Ακολουθεί --> Εγγραφή_Σε_Καλλιτέχνη : όχι
Απεγγραφή_Από_Καλλιτέχνη --> Βάση_Δεδομένων : Επιτυχής-Update
Εγγραφή_Σε_Καλλιτέχνη <--> Βάση_Δεδομένων : Επιτυχής-Update
Εγγραφή_Σε_Καλλιτέχνη --> Popup_Εγγραφής : Επιτυχής
Απεγγραφή_Από_Καλλιτέχνη --> Popup_Απεγγραφής : Επιτυχής
Εγγραφή_Σε_Καλλιτέχνη --> Popup_Error : Ανεπιτυχής
Απεγγραφή_Από_Καλλιτέχνη --> Popup_Error : Ανεπιτυχής
Popup_Error --> Γενικός_Χρήστης
Popup_Error --> Μενού_Πληροφοριών_Καλλιτέχνη
Popup_Απεγγραφής --> Γενικός_Χρήστης
Popup_Εγγραφής --> Γενικός_Χρήστης

@enduml