@startuml

title Follow/Unfollow Artist

left to right direction

skinparam shadowing false
skinparam roundcorner 10

' =====================================================
' ACTORS
' =====================================================

actor Γενικός_Χρήστης

' =====================================================
' BOUNDARY OBJECTS
' =====================================================

boundary Μενού_Αναζήτησης
boundary Μενού_Πληροφοριών_Καλλιτέχνη

' =====================================================
' CONTROL OBJECTS
' =====================================================

control Έλεγξε_Αν_Ήδη_Ακολουθεί
control Απεγγραφή_Από_Καλλιτέχνη
control Εγγραφή_Σε_Καλλιτέχνη

' =====================================================
' ENTITY OBJECTS
' =====================================================

entity Βάση_Δεδομένων

' =====================================================
' INTERACTIONS
' =====================================================

Γενικός_Χρήστης --> Μενού_Αναζήτησης: Κάνει αναζήτηση που περιέχει το όνομα ενός καλλιτέχνη
Μενού_Αναζήτησης --> Μενού_Πληροφοριών_Καλλιτέχνη : Επιλέγει το καλλιτέχνη 
Μενού_Πληροφοριών_Καλλιτέχνη --> Έλεγξε_Αν_Ήδη_Ακολουθεί : Χρήστης επιλέγει "Follow"
Έλεγξε_Αν_Ήδη_Ακολουθεί --> Απεγγραφή_Από_Καλλιτέχνη : ναι
Έλεγξε_Αν_Ήδη_Ακολουθεί --> Εγγραφή_Σε_Καλλιτέχνη : όχι
Απεγγραφή_Από_Καλλιτέχνη --> Βάση_Δεδομένων : Επιτυχής-Update
Εγγραφή_Σε_Καλλιτέχνη --> Βάση_Δεδομένων : Επιτυχής-Update
Εγγραφή_Σε_Καλλιτέχνη --> Toast_Εγγραφής : Επιτυχής
Απεγγραφή_Από_Καλλιτέχνη --> Toast_Απεγγραφής : Επιτυχής
Εγγραφή_Σε_Καλλιτέχνη --> Toast_Error : Ανεπιτυχής
Απεγγραφή_Από_Καλλιτέχνη --> Toast_Error : Ανεπιτυχής
Toast_Error --> Γενικός_Χρήστης
Toast_Error --> Μενού_Πληροφοριών_Καλλιτέχνη
Toast_Απεγγραφής --> Γενικός_Χρήστης
Toast_Εγγραφής --> Γενικός_Χρήστης

@enduml