@startuml

title Premium Purchase

left to right direction

skinparam shadowing false
skinparam roundcorner 10

' =====================================================
' ACTORS
' =====================================================

actor Γενικός_Χρήστης

' =====================================================
' BOUNDARY OBJECTS
' =====================================================

boundary Μενού_Πλοήγησης
boundary Οθόνη_Premium_Πακέτων
boundary Οθόνη_Επιτυχίας_Πληρωμής
boundary Error_Payment_Popup



' =====================================================
' CONTROL OBJECTS
' =====================================================

control Επιλογή_Στοιχεία_Πλοήγησης
control Διαδικασία_Πληρωμής
control Ερώτηση_Αυτόματης_Ανανέωσης
control Premium_Countdown

' =====================================================
' ENTITY OBJECTS
' =====================================================

entity Βάση_Δεδομένων
entity Τραπεζικό_Σύστημα

' =====================================================
' INTERACTIONS
' =====================================================
Γενικός_Χρήστης --> Μενού_Πλοήγησης 
Μενού_Πλοήγησης --> Επιλογή_Στοιχεία_Πλοήγησης
Επιλογή_Στοιχεία_Πλοήγησης --> Οθόνη_Premium_Πακέτων
Γενικός_Χρήστης --> Οθόνη_Premium_Πακέτων : Επιλέγει Premium Πακέτο
Οθόνη_Premium_Πακέτων --> Διαδικασία_Πληρωμής
Διαδικασία_Πληρωμής --> Τραπεζικό_Σύστημα : Βασική Ροή Payment Through Bank Account
Διαδικασία_Πληρωμής --> Οθόνη_Επιτυχίας_Πληρωμής : Επιτυχής
Οθόνη_Επιτυχίας_Πληρωμής --> Βάση_Δεδομένων : Set Premium αυτό που επιλέχθηκε, Set Plan_On_Renew = 0
Διαδικασία_Πληρωμής --> Error_Payment_Popup : Ανεπιτυχής
Error_Payment_Popup --> Γενικός_Χρήστης
Error_Payment_Popup --> Οθόνη_Premium_Πακέτων
' Δε ξέρω τι να βάλω για control εδώ, 150 render δεν έχουν νόημα
Οθόνη_Επιτυχίας_Πληρωμής --> Ερώτηση_Αυτόματης_Ανανέωσης 
Ερώτηση_Αυτόματης_Ανανέωσης -->  Βάση_Δεδομένων : Χρήστης έθεσε Plan_On_Renew = 0 ή όχι 0
Ερώτηση_Αυτόματης_Ανανέωσης --> Premium_Countdown : Ξεκινά αντίστροφη μέτρηση, βλέπε Premium Management



@enduml